apiVersion: v1
kind: Service
metadata:
  name: spring-boot
  labels:
    run: spring-boot
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    run: spring-boot